CMS/CMS.Presentation/Models/TrainerGroupViewModel.cs
using CMS.Application.Aggregates.TrainerGroup.Commands.CreateTrainerGroup;
using CMS.Application.Aggregates.TrainerGroup.Commands.EditTrainerGroup;
using CMS.Application.Aggregates.TrainerGroup.Queries.GetTrainerGroup;
using CMS.Application.Models;

namespace СMS.Models
{
    public class TrainerGroupViewModel
    {
        public PaginatedList<CMS.Application.Aggregates.TrainerGroup.Queries.GetTrainerGroups.TrainerGroup> List
        {
            get;
            set;
        }

        public CreateTrainerGroupCommand CreateModel
        {
            get;
            set;
        } = new CreateTrainerGroupCommand();

        public EditTrainerGroupCommand EditModel
        {
            get;
            set;
        } = new EditTrainerGroupCommand();

        public TrainerGroup Current
        {
            get;
            set;
        }
    }
}

CMS/CMS.Presentation/Controllers/TrainerGroupController.cs
using CMS.Application.Aggregates.Trainer.Queries.GetTrainer;
using CMS.Application.Aggregates.TrainerGroup.Commands.CreateTrainerGroup;
using CMS.Application.Aggregates.TrainerGroup.Commands.DeleteTrainerGroup;
using CMS.Application.Aggregates.TrainerGroup.Commands.EditTrainerGroup;
using CMS.Application.Aggregates.TrainerGroup.Queries.GetTrainerGroup;
using CMS.Application.Aggregates.TrainerGroup.Queries.GetTrainerGroups;
using CMS.Application.Aggregates.TrainerGroup.Queries.GetTrainerGroupsList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using СMS.Models;

namespace СMS.Controllers
{
    public class TrainerGroupController : BaseController
    {
        public TrainerGroupController(ILogger<TrainerGroupController> logger)
            : base(logger)
        {
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetModels(int? pageIndex = 1, int? pageSize = 10, Guid? id = null)
        {
            var result = new TrainerGroupViewModel();
            result.List = await Mediator.Send(new GetTrainerGroupsQuery(pageIndex, pageSize));
            if (id != null)
            {
                result.Current = await Mediator.Send(new GetTrainerGroupQuery() { TrainerGroupId = id.Value });
            }
            return View(result);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetModelsUsers( Guid? id = null)
        {
            var result = new TrainerGroupUserViewModel();
            result.TrainerGroups = await Mediator.Send(new GetTrainerGroupsListQuery());
            if (id != null)
            {
                result.Current = await Mediator.Send(new GetTrainerQuery() { TrainerId = id.Value });
            }
            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddModel(TrainerGroupViewModel command)
        {
            await Mediator.Send(new CreateTrainerGroupCommand()
            {
                Description = command.CreateModel.Description,
                Name = command.CreateModel.Name,
                VisualOrder = command.CreateModel.VisualOrder
            });
            return RedirectToAction("GetModels");
        }


        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateModel(TrainerGroupViewModel command, Guid TrainerGroupId)
        {
            await Mediator.Send(new EditTrainerGroupCommand()
            {
                TrainerGroupId = TrainerGroupId,
                Description = command.EditModel.Description,
                Name = command.EditModel.Name,
                VisualOrder = command.EditModel.VisualOrder
            });
            return RedirectToAction("GetModels");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<RedirectToActionResult> DeleteModelAsync(Guid id)
        {
            await Mediator.Send(new DeleteTrainerGroupCommand { TrainerGroupId = id });
            return RedirectToAction("GetModels");
        }
    }
}

CMS/CMS.Presentation/Views/TrainerGroup/GetModels.cshtml
@model СMS.Models.TrainerGroupViewModel
@{
    ViewData["Title"] = "Trainer Groups";
}
<div class="row mb-lg-3">
    <div class="col-md-6">
        <h4>Trainer Groups</h4>
    </div>
    <div class="col-md-6  text-right">
        <button type="button" class="btn btn-primary btn-block" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">Create Group</button>
    </div>
</div>
<div class="row mb-lg-3">
    <div class="col">
        @if (Model.List?.TotalCount > 0)
        {
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @if (Model.List?.PageIndex >= 2)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-route-pageIndex=@(@Model.List?.PageIndex-1)>Previous</a>
                        </li>
                    }

                    @for (int i = Model.List.PageIndex; i <= Model.List?.PageIndex + 5 && i <= Model.List?.TotalPages; i++)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-route-pageIndex=@i>@i</a>
                        </li>
                    }

                    @if (Model.List?.PageIndex < Model.List?.TotalPages)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-route-pageIndex=@(@Model.List?.PageIndex+1)>Next</a>
                        </li>
                    }
                </ul>
            </nav>
        }
    </div>
</div>
<div class="shadow p-3 mb-3 bg-white rounded">
    <table class="table table-hover">
        <tr>
            <th><a>Name</a></th>
            <th><a>Description</a></th>
            <th><a>Order</a></th>
            <th><a>Action</a></th>
        </tr>

        @if (Model != null)
        {
            @foreach (var group in Model.List?.Items)
            {
                <tr>
                    <td>@group.Name</td>
                    <td>@group.Description</td>
                    <td>@group.VisualOrder</td>
                    <td>
                        <ul class="nav nav-list">
                            <li style="list-style-type: none;" class="p-1">
                                <a class="btn btn-outline-warning  btn-sm" asp-controller="TrainerGroup" asp-action="GetModels" asp-route-id="@group.Id">
                                    <i class="fa fa-pencil"></i>
                                </a>
                            </li>
                            <li style="list-style-type: none;" class="p-1">
                                <a class="btn btn-outline-danger  btn-sm" asp-controller="TrainerGroup" asp-action="De" asp-route-id="@group.Id">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </li>
                        </ul>
                    </td>
                </tr>
            }

        }
    </table>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Group</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" enctype="multipart/form-data" asp-controller="TrainerGroup" asp-action="AddModel">
                <div class="modal-body">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col">
                        <div class="form-group mb-lg-2">
                            <label asp-for="@Model.CreateModel.Name">Name</label><br />
                            <input type="text" class="form-control" asp-for="@Model.CreateModel.Name" />
                        </div>
                        <div class="form-group  mb-lg-2">
                            <label asp-for="@Model.CreateModel.VisualOrder">Order</label><br />
                            <input type="number" class="form-control" asp-for="@Model.CreateModel.VisualOrder" />
                        </div>
                        <div class="form-group  mb-lg-2">
                            <label asp-for="@Model.CreateModel.Description">Description</label><br />
                            <textarea class="form-control" asp-for="@Model.CreateModel.Description" rows="3"></textarea>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>
@if (Model.Current != null)
{
    <div class="modal fade" id="EditModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit group</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" enctype="multipart/form-data" asp-controller="TrainerGroup" asp-action="UpdateModel" asp-route-TrainerGroupId="@Model.Current.Id">
                    <div class="modal-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="col">
                            <div class="form-group mb-lg-2">
                                <label asp-for="@Model.EditModel.Name">Name</label><br />
                                <input type="text" class="form-control" asp-for="@Model.EditModel.Name" value="@Model.Current.Name" />
                            </div>
                            <div class="form-group  mb-lg-2">
                                <label asp-for="@Model.EditModel.VisualOrder">Order</label><br />
                                <input type="number" class="form-control" asp-for="@Model.EditModel.VisualOrder" value="@Model.Current.VisualOrder" />
                            </div>
                            <div class="form-group  mb-lg-2">
                                <label asp-for="@Model.EditModel.Description">Description</label><br />
                                <textarea class="form-control" asp-for="@Model.EditModel.Description" rows="3">@Model.Current.Description.ToString()</textarea>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

<script>
    window.addEventListener('load', function () {
        const elemModal = document.querySelector('#EditModel');
        const modal = new bootstrap.Modal(elemModal);
        modal.show();
    });
</script>

CMS/CMS.Presentation/Views/TrainerGroup/GetModelsUsers.cshtml
@model СMS.Models.TrainerGroupUserViewModel
@{
    ViewData["Title"] = "Trainers";
}
<div class="row mb-lg-3">
    <div class="col-md-6">
        <h4>Trainers</h4>
    </div>
</div>
@if (Model.TrainerGroups != null)
{
    @foreach (var group in Model.TrainerGroups)
    {
        <div class="shadow p-3 mb-3 bg-white rounded">
            <h3>@group.Name</h3>
        <div class="container-fluid">
            <div class="d-flex flex-row flex-nowrap overflow-auto">
                @foreach (var trainer in group.Trainers)
                {
                    <div class="card bg-light" style="width: 20%; height: 100%;">
                        @if (trainer.Photo != null)
                        {
                            <img class="card-img-top" width="80%" height="80%" src="@String.Format("data:image/jpg;base64,{0}", Convert.ToBase64String(trainer.Photo))" alt="Card image cap">
                        }
                        <div class="card-body">
                            <h5 class="card-title">@trainer.FirstName @trainer.LastName</h5>
                            <a asp-controller="TrainerGroup" asp-action="GetModelsUsers" asp-route-id="@trainer.Id" class="btn btn-primary">
                                <i class="fa fa-info-circle"></i>
                            </a>
                        </div>
                    </div>
                }
                
            </div>
        </div>
        </div>
    }
}
@if (Model.Current != null)
{
    <div class="modal fade" id="Trainer" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">@Model.Current.FirstName @Model.Current.LastName</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-3">
                        @if (Model.Current.Photo != null)
                        {
                            <img width="100%" height="100%" src="@String.Format("data:image/jpg;base64,{0}", Convert.ToBase64String(@Model.Current.Photo))"/>
                        }
                        </div>
                        <div class="col-md-9">
                            <p>Description: @Model.Current.Description</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    window.addEventListener('load', function () {
        const elemModal = document.querySelector('#Trainer');
        const modal = new bootstrap.Modal(elemModal);
        modal.show();
    });
</script>