CMS/CMS.Presentation/Controllers/CourseController.cs
using CMS.Application.Aggregates.Course.Commands.CreateCourse;
using CMS.Application.Aggregates.Course.Commands.DeleteCourse;
using CMS.Application.Aggregates.Course.Commands.DeleteTrainer;
using CMS.Application.Aggregates.Course.Commands.EditCourse;
using CMS.Application.Aggregates.Course.Commands.EditTrainers;
using CMS.Application.Aggregates.Course.Queries.GetCourse;
using CMS.Application.Aggregates.Course.Queries.GetCourses;
using CMS.Application.Aggregates.CourseGroup.Queries.GetCourseGroupsList;
using CMS.Application.Aggregates.CourseType.Queries.GetCourseTypes;
using CMS.Application.Aggregates.Trainer.Queries.GetTrainer;
using CMS.Application.Aggregates.Trainer.Queries.GetTrainersList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using СMS.Models;

namespace СMS.Controllers
{
    public class CourseController : BaseController
    {
        public CourseController(ILogger<CourseController> logger)
            : base(logger)
        {
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetModels(int? pageIndex = 1, int? pageSize = 10)
        {
            var groups = await Mediator.Send(new GetCourseGroupsListQuery());
            ViewBag.Group = groups;
            var type = await Mediator.Send(new GetCourseTypesQuery());
            ViewBag.Type = type;
            var result = await Mediator.Send(new GetCoursesQuery(pageIndex, pageSize));
            return View(result);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetModelsUsers(int? pageIndex = 1, int? pageSize = 10)
        {
            var groups = await Mediator.Send(new GetCourseGroupsListQuery());
            ViewBag.Group = groups;
            var type = await Mediator.Send(new GetCourseTypesQuery());
            ViewBag.Type = type;
            var result = await Mediator.Send(new GetCoursesQuery(pageIndex, pageSize));
            return View(result);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetModel(Guid id, Guid? trainerId)
        {
            var result = new GetCourseViewModel();
            if (trainerId != null)
            {
                result.Trainer =  await Mediator.Send(new GetTrainerQuery() {TrainerId = trainerId.Value});
            }
            result.Course = await Mediator.Send(new GetCourseQuery { CourseId = id });
            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddModel()
        {
            ViewBag.Group = await Mediator.Send(new GetCourseGroupsListQuery());
            ViewBag.Type = await Mediator.Send(new GetCourseTypesQuery());
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddModel(CreateCourseCommand command)
        {
            await Mediator.Send(command);

            return RedirectToAction("GetModels");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateModel(Guid id)
        {
            ViewBag.Group = await Mediator.Send(new GetCourseGroupsListQuery());
            ViewBag.Type = await Mediator.Send(new GetCourseTypesQuery());
            ViewBag.Course = await Mediator.Send(new GetCourseQuery() {CourseId = id});
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateModel(EditCourseCommand command, Guid id)
        {
            command.CourseId = id;
            await Mediator.Send(command);

            return RedirectToAction("GetModels");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EditTrainers(Guid id)
        {
            var result = new EditCourseViewModel();

            result.CurrentCourse = await Mediator.Send(new GetCourseQuery() {CourseId = id});
            result.Trainers = await Mediator.Send(new GetTrainersListQuery());
            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EditTrainers(EditCourseViewModel model, Guid courseId)
        {
            model.EditTrainerCommand.CourseId = courseId;
            await Mediator.Send(model.EditTrainerCommand);

            return RedirectToAction("EditTrainers" ,new {id = courseId});
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteTrainer(Guid trainerId, Guid courseId)
        {

            await Mediator.Send(new DeleteTrainerCommand()
            {
                TrainerId = trainerId,
                CourseId = courseId
            });

            return RedirectToAction("EditTrainers" ,new { id = courseId });
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<RedirectToActionResult> DeleteModelAsync(Guid id)
        {
            await Mediator.Send(new DeleteCourseCommand { CourseId = id });
            return RedirectToAction("GetModels");
        }
    }
}

CMS/CMS.Presentation/Controllers/CourseGroupController.cs
using CMS.Application.Aggregates.CourseGroup.Commands.CreateCourseGroup;
using CMS.Application.Aggregates.CourseGroup.Commands.DeleteCourseGroup;
using CMS.Application.Aggregates.CourseGroup.Commands.EditCourseGroup;
using CMS.Application.Aggregates.CourseGroup.Queries.GetCourseGroup;
using CMS.Application.Aggregates.CourseGroup.Queries.GetCourseGroups;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using СMS.Models;

namespace СMS.Controllers
{
    public class CourseGroupController : BaseController
    {
        public CourseGroupController(ILogger<CourseGroupController> logger)
            : base(logger)
        {
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetModels(int? pageIndex = 1, int? pageSize = 10, Guid? id = null)
        {
            var result = new CourseGroupViewModel();
            result.List = await Mediator.Send(new GetCourseGroupsQuery(pageIndex, pageSize));
            if (id != null)
            {
                result.Current = await Mediator.Send(new GetCourseGroupQuery() {CourseId = id.Value});
            }
            return View(result);
        }
        
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddModel(CourseGroupViewModel command)
        {
            await Mediator.Send(new CreateCourseGroupCommand()
            {
                Description = command.CreateModel.Description,
                Name = command.CreateModel.Name,
                VisualOrder = command.CreateModel.VisualOrder
            });
            return RedirectToAction("GetModels");
        }


        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateModel(CourseGroupViewModel command, Guid CourseGroupId)
        {
            await Mediator.Send(new EditCourseGroupCommand()
            {
                CourseGroupid = CourseGroupId,
                Description = command.EditModel.Description,
                Name = command.EditModel.Name,
                VisualOrder = command.EditModel.VisualOrder
            });
            return RedirectToAction("GetModels");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<RedirectToActionResult> DeleteModelAsync(Guid id)
        {
            await Mediator.Send(new DeleteCourseGroupCommand { CourseGroupId = id });
            return RedirectToAction("GetModels");
        }
    }
}

CMS/CMS.Presentation/Controllers/TrainerController.cs
using CMS.Application.Aggregates.Trainer.Commands.CreateTrainer;
using CMS.Application.Aggregates.Trainer.Commands.DeleteTrainer;
using CMS.Application.Aggregates.Trainer.Commands.EditTrainer;
using CMS.Application.Aggregates.Trainer.Queries.GetTrainer;
using CMS.Application.Aggregates.Trainer.Queries.GetTrainers;
using CMS.Application.Aggregates.TrainerGroup.Queries.GetTrainerGroupsList;
using CMS.Application.Aggregates.User.Queries.GetUsersList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace СMS.Controllers
{
    public class TrainerController : BaseController
    {
        public TrainerController(ILogger<TrainerController> logger)
            : base(logger)
        {
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetModels(int? pageIndex = 1, int? pageSize = 10)
        {
            var result = await Mediator.Send(new GetTrainersQuery(pageIndex, pageSize));
            return View(result);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetModel(Guid id)
        {
            var result = await Mediator.Send(new GetTrainerQuery { TrainerId = id });
            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddModel()
        {
            ViewBag.Group = await Mediator.Send(new GetTrainerGroupsListQuery());
            ViewBag.Users = await Mediator.Send(new GetUsersListQuery());
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddModel(CreateTrainerCommand command)
        {
            await Mediator.Send(command);
            return RedirectToAction("GetModels");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateModel(Guid id)
        {
            ViewBag.Trainer = await Mediator.Send(new GetTrainerQuery() { TrainerId = id });
            ViewBag.Group = await Mediator.Send(new GetTrainerGroupsListQuery());
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateModel(EditTrainerCommand command, Guid id)
        {
            command.TrainerId = id;
            await Mediator.Send(command);
            return RedirectToAction("GetModels");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<RedirectToActionResult> DeleteModelAsync(Guid id)
        {
            await Mediator.Send(new DeleteTrainerCommand { TrainerId = id });
            return RedirectToAction("GetModels");
        }
    }
}

CMS/CMS.Presentation/Controllers/UserController.cs
using CMS.Application.Aggregates.Roles.Queries.GetRoles;
using CMS.Application.Aggregates.User.Commands.ChangePassword;
using CMS.Application.Aggregates.User.Commands.ChangeRoles;
using CMS.Application.Aggregates.User.Commands.DeleteRole;
using CMS.Application.Aggregates.User.Queries.GetUser;
using CMS.Application.Aggregates.User.Queries.GetUsers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.EntityFrameworkCore;
using СMS.Models;

namespace СMS.Controllers
{
    public class UserController : BaseController
    {
        public UserController(ILogger<UserController> logger)
            : base(logger)
        {
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetModels(int? pageIndex = 1, int? pageSize = 10)
        {
            var result = await Mediator.Send(new GetUsersQuery(pageIndex, pageSize));
            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetModel(Guid id)
        {
            var result = await Mediator.Send(new GetUserQuery { UserId = id });

            return View(result);
        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateModel(Guid id)
        {
            var result = new UpdateUserViewModel();
            result.User = await Mediator.Send(new GetUserQuery { UserId = id });
            var roles = await Mediator.Send(new GetRolesQuery());
            ViewBag.Roles = roles;
            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ResetPassword(UpdateUserViewModel model, Guid UserId)
        {
            await Mediator.Send(new ChangePasswordCommand()
            {
                UserId = UserId,
                Password = model.PasswordCommand.Password,
                ConfirmPassword = model.PasswordCommand.ConfirmPassword
            });
            return RedirectToAction("GetModel", new { id = UserId });
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> EditRoles(UpdateUserViewModel model, Guid UserId)
        {
            await Mediator.Send(new ChangeRolesCommand()
            {
                UserId = UserId,
                RoleIds = model.RolesCommand.RoleIds
            });
            return RedirectToAction("UpdateModel", new { id = UserId });
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteRoles(Guid roleId, Guid userId)
        {
            await Mediator.Send(new DeleteRoleCommand()
            {
                RoleId = roleId,
                UserId = userId
            });
            return RedirectToAction("UpdateModel", new { id = userId});
        }
    }
}

CMS/CMS.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container col-md-9">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-success"> @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="nav-link btn btn-link text-primary">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-primary"  asp-controller="Account" asp-action="Register">SingIn</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-controller="Account" asp-action="Login">SingOn</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div class="col-md-2">
            <div class="sidenav">
                <ul class="nav nav-list">
                    <li class="nav-link">
                        <a asp-controller="Course" asp-action="GetModelsUsers">Courses</a>
                    </li>
                    <li class="nav-link">
                        <a asp-controller="TrainerGroup" asp-action="GetModelsUsers">Trainers</a>
                    </li>
                    <hr align="center" width="100%" color="white" />
                    <li class="nav-link">
                        <a asp-controller="Course" asp-action="GetModels">Course List</a>
                    </li>
                    <li class="nav-link">
                        <a asp-controller="CourseGroup" asp-action="GetModels">Course Groups</a>
                    </li>
                    <li class="nav-link">
                        <a asp-controller="Trainer" asp-action="GetModels">Trainers List</a>
                    </li>
                    <li class="nav-link">
                        <a asp-controller="TrainerGroup" asp-action="GetModels">Trainers Groups</a>
                    </li>
                    <li class="nav-link">
                        <a asp-controller="User" asp-action="GetModels">Users</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>